### ISSUE TITLE
[Help Wanted] Keras example

### ISSUE THREAD

**Issue by INF800** [haven-ai/haven-ai#36]
Hi,

I want to test this project. I want to do so by running multiple keras hyperparameter tuning examples. 

To be specific, I am planning to implement all the experiments in this blog https://machinelearningmastery.com/how-to-develop-a-cnn-from-scratch-for-cifar-10-photo-classification/

Will be updating my progress here.

**Comment by INF800** [comment]
Is there any keras example already available with haven so that I can steal code from there?

**Comment by IssamLaradji** [comment]
Hey thanks for stopping by! I don't think there is a keras project with haven-ai, but you could start the code base from this https://github.com/haven-ai/haven-ai/blob/master/trainval.py where you would replace the `model` with a keras model. 

If you have a repo for your project that I could look over, I would be happy to help you with integrating haven-ai.

**Comment by INF800** [comment]
I made a basic example with keras in this repo: https://github.com/INF800/keras-haven/tree/setup/basic-keras-example

### What I did

1. dataloader
    - keras supports generator so used data generator in keras-specific way which can be used exactly like pytorch dataloaders https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/src/datasets.py#L41

2. model
    - Created model by subclassing the `tf.keras.Model` class. By doing this, we can use keras model like pytorch model. https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/src/models.py#L20

3. train val loop
    - Wrote custom loop for keras model using `model.train_on_batch(...)`  https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/trainval.py#L63
    - Cross-checked results with `model.fit`. No issues.

This resulted in the following graphs for three different learning rates over 5 epochs on MNIST dataset.

![image](https://user-images.githubusercontent.com/45640029/128268439-70cf37ef-d909-48ca-8bfd-f9a725a316f9.png)

**Comment by INF800** [comment]
I may need some changes in your repo for the following: (in no particular order)

1. saving keras model.
    - Need something like `cm.save_keras` because we cannot save keras model using pkl. Please have a look at this https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/trainval.py#L81

2. Can we resume keras training from a specific epoch number?  https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/trainval.py#L62

3. Need a way to load keras model using checkpoint manager https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/trainval.py#L57

**Comment by INF800** [comment]
@IssamLaradji  Please have a look at the repo in your free time and let me know your insights. I may also need your help in running experiments on cluster https://github.com/haven-ai/haven-ai#4-run-experiments-on-the-cluster

**Comment by INF800** [comment]
Can you also point me out to a basic images saving example ?

**Comment by IssamLaradji** [comment]
This looks great! I enjoyed going through your clean code, and I appreciate the bullet points. , Here are my answers to the bullet points,

**Saving/Loading Models**

(1) For saving a `keras` model, we wouldn't need a special helper, the model could be explicitly saved as `model.save(os.path.join(savedir, 'model.pth'))`. So you could replace `hu.save_torch` with that one.
(2) (3) Similarly, for loading/resuming a `keras` model we could use this 
```
model = keras.models.load_model(os.path.join(savedir, 'model.pth'))
``` 
instead of `model.set_state_dict(state_dict)`. You just need to check if the path `os.path.join(savedir, 'model.pth')` exists in order to resume.

It seems like we don't need to use the checkpoint manager for saving and loading the model, making things simpler! :))

**Running on Cluster**
Do you have access to a job schedule like `slurm` or `gcp` for running experiments on the cluster?

**Saving Images**
To be able to view the images on the jupyter dashboard, images should be saved in the folder `os.path.join(savedir, 'images')`. They can be in `.png`, `.jpg` or even `.gif`

In line 78 of your `trainval.py` (https://github.com/INF800/keras-haven/blob/6460081615e1c3b06cc0fa3cb4e07267d9a6332b/trainval.py#L78) add lines like these and they will be displayed in the dashboard on jupyter 

```
image = np.zeros((200,200, 3))
hu.save_image(os.path.join(savedir, 'images', 'example.png')  image)
```

**Comment by INF800** [comment]
Thanks!! Made the changes in keras as suggested and everything was working perfect. Picking up #35 now.

**Comment by INF800** [comment]
I will try to setup cluster in #35

**Comment by IssamLaradji** [comment]
great to hear! :))
